### ISSUE TITLE
アクセスカウンター実装

### ISSUE THREAD

**Issue by morotesovtannu** [fediminhayaclubja/everyone-website#1]
ごめんなさい
@cicada-sss せせせのほめぱげと同じやつを羊と置き換えて実装してもらえませんか？

**Comment by cicada-sss** [comment]
@morotesovtannu 
後でやってみますー！
ちなみに、例のサイトはこのやり方で実装してます
https://qiita.com/Nekoya3/items/6aab28a628e9fc111c63
スプレッドシート用意して直JSで書くことになりそう

**Comment by morotesovtannu** [comment]
ありがとうございます！

**Comment by cicada-sss** [comment]
@morotesovtannu 
https://github.com/fediminhayaclubja/everyone-website/commit/91966e2db50f5b74599a381cf6d2a2f40d62c9af
入れましたー。mainにそのまま入れましたがなんか問題あったら言ってください！
<img width="480" alt="スクリーンショット 2022-04-27 0 40 15" src="https://user-images.githubusercontent.com/27691075/165339047-bcce7062-071e-4c28-b13c-8ca6473e1fbd.png">

**Comment by morotesovtannu** [comment]
いえいえありがとうございます！
ではこのIssue閉じますね
